// documentation/src/pages/examples/AvatarExample.tsx
import { useOverflowedItems } from "overflowed/react";

// @docs-line-hidden
import styles from "./AvatarExample.module.css";
// @docs-line-hidden
import { people } from "./data";

export const AvatarExample = () => {
	const [visiblePeople, overflowedPeople, { getContainerProps, getIndicatorProps }] = useOverflowedItems(people);

	return (
		<ul
			// @docs-line-hidden
			className={styles["container"]}
			{...getContainerProps()}
		>
			{visiblePeople.map(([person, getItemProps]) => (
				<li
					key={person.id}
					// @docs-line-hidden
					className={styles["avatar"]}
					{...getItemProps({ style: { backgroundColor: person.color } })}
				>
					{person.initials}
				</li>
			))}
			<li
				// @docs-line-hidden
				className={styles["avatar"]}
				{...getIndicatorProps()}
			>
				+{overflowedPeople.length}
			</li>
		</ul>
	);
};

// documentation/src/pages/examples/_AvatarExample.svelte
<script lang="ts">
	import { overflowedItems } from "overflowed/svelte";

	// @docs-line-hidden
	import "./_AvatarExample.module.css";
	// @docs-line-hidden
	import { people } from "./_data";

	let [visiblePeople, overflowedPeople, action] = overflowedItems(people, (newVisiblePeople, newOverflowedPeople) => {
		visiblePeople = newVisiblePeople;
		overflowedPeople = newOverflowedPeople;
	});
</script>

<div class="container" use:action.container>
	{#each visiblePeople as person, index}
		<div class="avatar" use:action.item={index}>
			{person.initials}
		</div>
	{/each}
	<div class="avatar" use:action.indicator>
		+{overflowedPeople.length}
	</div>
</div>
